### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by hardianlawi** [allenai/acl2022-zerofewshot-tutorial#2]
Hi @sameersingh 

Thank you so much for creating this amazing tutorial and sharing the slides. I am wondering if there is any recording and if it's shared anywhere as I couldn't find it. I think that would be tremendously helpful for people who don't have access to the conference.

Best regards

**Comment by rloganiv** [comment]
Hi @hardianlawi,

The video is available at: https://underline.io/events/284/sessions?eventSessionId=10748
